#!/usr/bin/env python3
"""Capture triggered PicoScope waveforms as the CSV format used by the analysis.

Supported PicoSDK wrappers are ps2000a, ps3000a, ps4000a and ps5000a.  The
synthetic mode exercises the complete scan without requiring a scope.
"""

from __future__ import annotations

import argparse
import csv
import ctypes
import importlib
import json
import math
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np


SUPPORTED_DRIVERS = ("ps5000a", "ps4000a", "ps3000a", "ps2000a")
RANGE_NAMES = {
    10: "10MV",
    20: "20MV",
    50: "50MV",
    100: "100MV",
    200: "200MV",
    500: "500MV",
    1000: "1V",
    2000: "2V",
    5000: "5V",
    10000: "10V",
    20000: "20V",
    50000: "50V",
}


def choose_range(requested_mv: int) -> int:
    for range_mv in sorted(RANGE_NAMES):
        if range_mv >= requested_mv:
            return range_mv
    raise ValueError(f"Requested range {requested_mv} mV exceeds supported ranges")


def write_waveform_csv(
    path: Path,
    time_ns: np.ndarray,
    channels_mv: dict[str, np.ndarray],
) -> None:
    channel_names = list(channels_mv)
    values = np.column_stack([time_ns] + [channels_mv[name] for name in channel_names])
    with path.open("w", encoding="utf-8") as handle:
        handle.write("Time," + ",".join(f"Channel {name}" for name in channel_names) + "\n")
        handle.write("(ns)," + ",".join("(mV)" for _ in channel_names) + "\n")
        handle.write("Generated by automated_vbr_scan\n")
        np.savetxt(handle, values, delimiter=",", fmt="%.7g")


def pulse_shape(time_ns: np.ndarray, arrival_ns: float) -> np.ndarray:
    elapsed = time_ns - arrival_ns
    positive = np.maximum(elapsed, 0.0)
    pulse = (1.0 - np.exp(-positive / 2.5)) * np.exp(-positive / 38.0)
    pulse[elapsed < 0] = 0.0
    peak = np.max(pulse)
    return pulse / peak if peak > 0 else pulse


def synthetic_capture(args: argparse.Namespace, output: Path) -> dict[str, object]:
    rng = np.random.default_rng(args.seed)
    samples = int(round((args.pre_trigger_ns + args.post_trigger_ns) / args.sample_interval_ns)) + 1
    time_ns = np.linspace(-args.pre_trigger_ns, args.post_trigger_ns, samples)
    probabilities = np.asarray([0.20, 0.38, 0.24, 0.12, 0.06])
    pe_values = np.arange(1, len(probabilities) + 1)
    gap_a = max(5.0, args.synthetic_gain_a * (args.bias_v - args.synthetic_vbr_a))
    gap_b = max(5.0, args.synthetic_gain_b * (args.bias_v - args.synthetic_vbr_b))

    for event in range(args.events):
        arrival = rng.normal(20.0, 1.0)
        shape = pulse_shape(time_ns, arrival)
        pe_a = rng.choice(pe_values, p=probabilities)
        pe_b = rng.choice(pe_values, p=probabilities)
        baseline_a = rng.normal(0.0, 0.7)
        baseline_b = rng.normal(0.0, 0.7)
        channel_a = baseline_a + pe_a * gap_a * shape + rng.normal(0.0, 1.8, samples)
        channel_b = baseline_b + pe_b * gap_b * shape + rng.normal(0.0, 1.8, samples)
        write_waveform_csv(
            output / f"event_{event:06d}.csv",
            time_ns,
            {"A": channel_a, "B": channel_b},
        )

    return {
        "mode": "synthetic",
        "events": args.events,
        "bias_v": args.bias_v,
        "sample_interval_ns": args.sample_interval_ns,
        "samples_per_event": samples,
        "trigger_channel": args.trigger_channel,
        "trigger_mv": args.trigger_mv,
        "probe_attenuation": args.probe_attenuation,
        "synthetic_gap_a_mv": gap_a,
        "synthetic_gap_b_mv": gap_b,
    }


class PicoBlockScope:
    def __init__(self, requested_driver: str, range_mv: int) -> None:
        self.requested_driver = requested_driver
        self.range_mv = choose_range(range_mv)
        self.driver = ""
        self.api = None
        self.handle = ctypes.c_int16()
        self.max_adc = ctypes.c_int16()
        self.channel_ranges: dict[str, int] = {}

    @property
    def upper(self) -> str:
        return self.driver.upper()

    def call(self, suffix: str):
        return getattr(self.api, f"{self.driver}{suffix}")

    def enum(self, group: str, value: str) -> int:
        table = getattr(self.api, f"{self.upper}_{group}")
        return table[f"{self.upper}_{value}"]

    def _open_driver(self, driver: str) -> None:
        self.driver = driver
        module = importlib.import_module(f"picosdk.{driver}")
        self.api = getattr(module, driver, module)
        self.handle = ctypes.c_int16()
        if driver == "ps5000a":
            resolution = self.api.PS5000A_DEVICE_RESOLUTION["PS5000A_DR_12BIT"]
            status = self.call("OpenUnit")(ctypes.byref(self.handle), None, resolution)
        else:
            status = self.call("OpenUnit")(ctypes.byref(self.handle), None)
        if status != 0:
            try:
                if self.handle.value:
                    power_status = self.call("ChangePowerSource")(self.handle, status)
                    if power_status == 0:
                        status = 0
            except Exception:
                pass
        if status != 0:
            raise RuntimeError(f"{driver} OpenUnit returned Pico status {status}")
        status = self.call("MaximumValue")(self.handle, ctypes.byref(self.max_adc))
        if status != 0:
            raise RuntimeError(f"{driver} MaximumValue returned Pico status {status}")

    def open(self) -> None:
        drivers = SUPPORTED_DRIVERS if self.requested_driver == "auto" else (self.requested_driver,)
        errors: list[str] = []
        for driver in drivers:
            try:
                self._open_driver(driver)
                return
            except Exception as exc:
                errors.append(f"{driver}: {exc}")
                try:
                    if self.handle.value and self.api is not None:
                        self.call("CloseUnit")(self.handle)
                except Exception:
                    pass
        raise RuntimeError("No supported PicoScope opened. " + " | ".join(errors))

    def close(self) -> None:
        if self.api is not None and self.handle.value:
            try:
                self.call("Stop")(self.handle)
            finally:
                self.call("CloseUnit")(self.handle)

    def configure_channels(
        self,
        active_channels: str | tuple[str, ...] | list[str],
        range_mv_by_channel: dict[str, int] | None = None,
    ) -> None:
        if isinstance(active_channels, str):
            active = {active_channels}
        else:
            active = set(active_channels)
        if not active or not active.issubset({"A", "B", "C", "D"}):
            raise ValueError("active channels must be a non-empty subset of A, B, C and D")
        requested_ranges = range_mv_by_channel or {}
        coupling = self.enum("COUPLING", "DC")
        for channel in ("A", "B", "C", "D"):
            channel_range = choose_range(requested_ranges.get(channel, self.range_mv))
            range_enum = self.enum("RANGE", RANGE_NAMES[channel_range])
            status = self.call("SetChannel")(
                self.handle,
                self.enum("CHANNEL", f"CHANNEL_{channel}"),
                int(channel in active),
                coupling,
                range_enum,
                0.0,
            )
            if status != 0:
                raise RuntimeError(f"SetChannel {channel} returned Pico status {status}")
            if channel in active:
                self.channel_ranges[channel] = channel_range

    def configure_trigger(
        self, channel: str, trigger_mv: float, auto_trigger_ms: int, enabled: bool = True
    ) -> None:
        channel_range = self.channel_ranges.get(channel, self.range_mv)
        threshold = round(trigger_mv * self.max_adc.value / channel_range)
        threshold = max(-self.max_adc.value, min(self.max_adc.value, threshold))
        status = self.call("SetSimpleTrigger")(
            self.handle,
            int(enabled),
            self.enum("CHANNEL", f"CHANNEL_{channel}"),
            threshold,
            self.enum("THRESHOLD_DIRECTION", "RISING"),
            0,
            auto_trigger_ms,
        )
        if status != 0:
            raise RuntimeError(f"SetSimpleTrigger returned Pico status {status}")

    def configure_coincidence_trigger(
        self,
        first_channel: str,
        first_trigger_mv: float,
        second_channel: str,
        second_trigger_mv: float,
        auto_trigger_ms: int,
    ) -> None:
        """Require two analogue channels to be above threshold simultaneously.

        The 3406B used for the scintillator study is driven through ps3000a.
        This deliberately uses the SDK advanced-trigger API rather than trying
        to infer a reference coincidence after a one-channel trigger.
        """
        if self.driver != "ps3000a":
            raise RuntimeError("analogue coincidence triggering currently requires ps3000a")
        if first_channel == second_channel:
            raise ValueError("coincidence channels must be different")
        if first_channel not in self.channel_ranges or second_channel not in self.channel_ranges:
            raise ValueError("both coincidence channels must be enabled")

        state_true = self.enum("TRIGGER_STATE", "CONDITION_TRUE")
        state_dont_care = self.enum("TRIGGER_STATE", "CONDITION_DONT_CARE")
        conditions = self.api.PS3000A_TRIGGER_CONDITIONS(
            *(
                state_true if channel in {first_channel, second_channel} else state_dont_care
                for channel in ("A", "B", "C", "D")
            ),
            state_dont_care,
            state_dont_care,
            state_dont_care,
        )
        status = self.call("SetTriggerChannelConditions")(
            self.handle, ctypes.byref(conditions), 1
        )
        if status != 0:
            raise RuntimeError(f"SetTriggerChannelConditions returned Pico status {status}")

        def properties(channel: str, trigger_mv: float):
            channel_range = self.channel_ranges[channel]
            threshold = round(trigger_mv * self.max_adc.value / channel_range)
            threshold = max(-self.max_adc.value, min(self.max_adc.value, threshold))
            return self.api.PS3000A_TRIGGER_CHANNEL_PROPERTIES(
                threshold,
                0,
                threshold,
                0,
                self.enum("CHANNEL", f"CHANNEL_{channel}"),
                self.enum("THRESHOLD_MODE", "LEVEL"),
            )

        trigger_properties = (self.api.PS3000A_TRIGGER_CHANNEL_PROPERTIES * 2)(
            properties(first_channel, first_trigger_mv),
            properties(second_channel, second_trigger_mv),
        )
        status = self.call("SetTriggerChannelProperties")(
            self.handle,
            trigger_properties,
            2,
            0,
            auto_trigger_ms,
        )
        if status != 0:
            raise RuntimeError(f"SetTriggerChannelProperties returned Pico status {status}")

        rising = self.enum("THRESHOLD_DIRECTION", "RISING")
        none = self.enum("THRESHOLD_DIRECTION", "NONE")
        directions = [rising if channel in {first_channel, second_channel} else none for channel in ("A", "B", "C", "D")]
        status = self.call("SetTriggerChannelDirections")(
            self.handle,
            *directions,
            none,
            none,
        )
        if status != 0:
            raise RuntimeError(f"SetTriggerChannelDirections returned Pico status {status}")

    def find_timebase(self, sample_count: int, requested_interval_ns: float) -> tuple[int, float]:
        best: tuple[float, int, float] | None = None
        for timebase in range(0, 1000):
            interval = ctypes.c_float()
            maximum_samples = ctypes.c_int32()
            try:
                status = self.call("GetTimebase2")(
                    self.handle,
                    timebase,
                    sample_count,
                    ctypes.byref(interval),
                    0,
                    ctypes.byref(maximum_samples),
                    0,
                )
            except TypeError:
                status = self.call("GetTimebase2")(
                    self.handle,
                    timebase,
                    sample_count,
                    ctypes.byref(interval),
                    ctypes.byref(maximum_samples),
                    0,
                )
            if status != 0 or maximum_samples.value < sample_count or interval.value <= 0:
                continue
            score = abs(math.log(interval.value / requested_interval_ns))
            if best is None or score < best[0]:
                best = (score, timebase, float(interval.value))
            if interval.value >= requested_interval_ns and best is not None:
                break
        if best is None:
            raise RuntimeError("No PicoScope timebase can provide the requested capture")
        return best[1], best[2]

    def capture_channels(
        self,
        pre_samples: int,
        post_samples: int,
        timebase: int,
        active_channels: tuple[str, ...] | list[str],
    ) -> tuple[dict[str, np.ndarray], int]:
        sample_count = pre_samples + post_samples
        buffers: dict[str, ctypes.Array] = {}
        ratio_mode = self.enum("RATIO_MODE", "RATIO_MODE_NONE")
        for channel in active_channels:
            maximum = (ctypes.c_int16 * sample_count)()
            minimum = (ctypes.c_int16 * sample_count)()
            status = self.call("SetDataBuffers")(
                self.handle,
                self.enum("CHANNEL", f"CHANNEL_{channel}"),
                ctypes.byref(maximum),
                ctypes.byref(minimum),
                sample_count,
                0,
                ratio_mode,
            )
            if status != 0:
                raise RuntimeError(f"SetDataBuffers {channel} returned Pico status {status}")
            buffers[channel] = maximum

        time_indisposed_ms = ctypes.c_int32()
        run_block = self.call("RunBlock")
        common_arguments = (
            self.handle,
            pre_samples,
            post_samples,
            timebase,
        )
        if len(getattr(run_block, "argtypes", ())) == 9:
            status = run_block(
                *common_arguments,
                1,
                ctypes.byref(time_indisposed_ms),
                0,
                None,
                None,
            )
        else:
            status = run_block(
                *common_arguments,
                ctypes.byref(time_indisposed_ms),
                0,
                None,
                None,
            )
        if status != 0:
            raise RuntimeError(f"RunBlock returned Pico status {status}")

        ready = ctypes.c_int16(0)
        while not ready.value:
            status = self.call("IsReady")(self.handle, ctypes.byref(ready))
            if status != 0:
                raise RuntimeError(f"IsReady returned Pico status {status}")
            time.sleep(0.001)

        returned_samples = ctypes.c_int32(sample_count)
        overflow = ctypes.c_int16()
        status = self.call("GetValues")(
            self.handle,
            0,
            ctypes.byref(returned_samples),
            1,
            ratio_mode,
            0,
            ctypes.byref(overflow),
        )
        if status != 0:
            raise RuntimeError(f"GetValues returned Pico status {status}")
        n = returned_samples.value
        traces = {
            channel: np.ctypeslib.as_array(buffer)[:n].astype(float)
            * self.channel_ranges.get(channel, self.range_mv)
            / self.max_adc.value
            for channel, buffer in buffers.items()
        }
        return traces, int(overflow.value)

def hardware_capture(args: argparse.Namespace, output: Path) -> dict[str, object]:
    scope = PicoBlockScope(args.driver, args.range_mv)
    scope.open()
    try:
        scope.configure_channels(args.trigger_channel)
        scope_input_trigger_mv = args.trigger_mv / args.probe_attenuation
        scope.configure_trigger(
            args.trigger_channel,
            scope_input_trigger_mv,
            args.auto_trigger_ms,
            enabled=not args.no_trigger,
        )
        approximate_samples = int(round((args.pre_trigger_ns + args.post_trigger_ns) / args.sample_interval_ns)) + 1
        timebase, actual_interval_ns = scope.find_timebase(approximate_samples, args.sample_interval_ns)
        pre_samples = int(round(args.pre_trigger_ns / actual_interval_ns))
        post_samples = int(round(args.post_trigger_ns / actual_interval_ns)) + 1
        time_ns = (np.arange(pre_samples + post_samples) - pre_samples) * actual_interval_ns
        overflow_events = 0
        event_status: list[tuple[int, int]] = []
        started = time.monotonic()
        for event in range(args.events):
            traces, overflow = scope.capture_channels(
                pre_samples,
                post_samples,
                timebase,
                (args.trigger_channel,),
            )
            overflow_events += int(bool(overflow))
            event_status.append((event, int(bool(overflow))))
            write_waveform_csv(
                output / f"event_{event:06d}.csv",
                time_ns[: len(traces[args.trigger_channel])],
                {args.trigger_channel: traces[args.trigger_channel] * args.probe_attenuation},
            )
            if (event + 1) % 100 == 0:
                elapsed = time.monotonic() - started
                rate = (event + 1) / elapsed if elapsed > 0 else 0.0
                print(f"captured {event + 1}/{args.events} events ({rate:.1f} events/s)", flush=True)
        with (output / "event_status.csv").open("w", newline="", encoding="utf-8") as handle:
            writer = csv.writer(handle)
            writer.writerow(["event", "overflow"])
            writer.writerows(event_status)
        return {
            "mode": "hardware",
            "driver": scope.driver,
            "events": args.events,
            "overflow_events": overflow_events,
            "range_mv": scope.range_mv,
            "scope_input_range_mv": scope.range_mv,
            "reported_range_mv": scope.range_mv * args.probe_attenuation,
            "probe_attenuation": args.probe_attenuation,
            "timebase": timebase,
            "sample_interval_ns": actual_interval_ns,
            "pre_samples": pre_samples,
            "post_samples": post_samples,
            "trigger_channel": args.trigger_channel,
            "enabled_channels": [args.trigger_channel],
            "trigger_mv": args.trigger_mv,
            "scope_input_trigger_mv": scope_input_trigger_mv,
            "trigger_enabled": not args.no_trigger,
        }
    finally:
        scope.close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--events", type=int, default=10000)
    parser.add_argument("--bias-v", type=float)
    parser.add_argument("--driver", choices=("auto",) + SUPPORTED_DRIVERS, default="auto")
    parser.add_argument("--range-mv", type=int, default=1000)
    parser.add_argument(
        "--probe-attenuation",
        type=float,
        default=1.0,
        help="probe attenuation ratio; saved voltages and trigger-mv are probe-tip values",
    )
    parser.add_argument("--sample-interval-ns", type=float, default=1.0)
    parser.add_argument("--pre-trigger-ns", type=float, default=100.0)
    parser.add_argument("--post-trigger-ns", type=float, default=400.0)
    parser.add_argument("--trigger-channel", choices=["A", "B", "C", "D"], default="A")
    parser.add_argument("--trigger-mv", type=float, default=80.0)
    parser.add_argument("--auto-trigger-ms", type=int, default=1000)
    parser.add_argument(
        "--no-trigger",
        action="store_true",
        help="disable the hardware trigger for rapid random pedestal captures",
    )
    parser.add_argument("--synthetic", action="store_true")
    parser.add_argument("--synthetic-vbr-a", type=float, default=51.2)
    parser.add_argument("--synthetic-vbr-b", type=float, default=51.5)
    parser.add_argument("--synthetic-gain-a", type=float, default=12.0)
    parser.add_argument("--synthetic-gain-b", type=float, default=10.0)
    parser.add_argument("--seed", type=int, default=12345)
    parser.add_argument("--probe", action="store_true", help="open the scope, report its PicoSDK family, then close")
    args = parser.parse_args()

    if not math.isfinite(args.probe_attenuation) or args.probe_attenuation <= 0:
        parser.error("--probe-attenuation must be a positive finite number")

    if args.probe:
        scope = PicoBlockScope(args.driver, args.range_mv)
        scope.open()
        try:
            print(
                json.dumps(
                    {
                        "driver": scope.driver,
                        "maximum_adc": scope.max_adc.value,
                        "selected_range_mv": scope.range_mv,
                        "reported_range_mv": scope.range_mv * args.probe_attenuation,
                        "probe_attenuation": args.probe_attenuation,
                    },
                    indent=2,
                )
            )
        finally:
            scope.close()
        return
    if args.output is None or args.bias_v is None:
        parser.error("--output and --bias-v are required unless --probe is used")
    if args.events < 1:
        parser.error("--events must be positive")
    args.output.mkdir(parents=True, exist_ok=False)
    metadata = synthetic_capture(args, args.output) if args.synthetic else hardware_capture(args, args.output)
    metadata.update(
        {
            "captured_at_utc": datetime.now(timezone.utc).isoformat(),
            "output": str(args.output),
        }
    )
    (args.output / "capture_metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
