#!/usr/bin/env python3
"""Capture four-channel waveforms for a reference-triggered scintillator test."""

from __future__ import annotations

import argparse
import csv
import json
import math
import time
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

from pico_capture import PicoBlockScope, SUPPORTED_DRIVERS, pulse_shape


CHANNELS = ("A", "B", "C", "D")


def parse_channels(text: str) -> tuple[str, ...]:
    channels = tuple(dict.fromkeys(item.strip().upper() for item in text.split(",") if item.strip()))
    if not channels or any(channel not in CHANNELS for channel in channels):
        raise argparse.ArgumentTypeError("channels must be a comma-separated subset of A,B,C,D")
    return channels


def parse_ranges(text: str) -> dict[str, int]:
    ranges: dict[str, int] = {}
    try:
        for item in text.split(","):
            channel, value = item.split("=", 1)
            channel = channel.strip().upper()
            if channel not in CHANNELS:
                raise ValueError(channel)
            ranges[channel] = int(value, 0)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            "ranges must look like A=500,B=500,C=500,D=500 in scope-input mV"
        ) from exc
    return ranges


def parse_attenuations(text: str) -> dict[str, float]:
    attenuations: dict[str, float] = {}
    try:
        for item in text.split(","):
            channel, value = item.split("=", 1)
            channel = channel.strip().upper()
            if channel not in CHANNELS:
                raise ValueError(channel)
            attenuations[channel] = float(value)
    except ValueError as exc:
        raise argparse.ArgumentTypeError(
            "attenuations must look like A=10,B=10,C=1,D=1"
        ) from exc
    return attenuations


def write_waveform(path: Path, time_ns: np.ndarray, traces: dict[str, np.ndarray]) -> None:
    values = np.column_stack([time_ns, *(traces[channel] for channel in CHANNELS)])
    with path.open("w", encoding="utf-8") as handle:
        handle.write("Time,Channel A,Channel B,Channel C,Channel D\n")
        handle.write("(ns),(mV),(mV),(mV),(mV)\n")
        handle.write("Generated by pico_scintillator_capture\n")
        np.savetxt(handle, values, delimiter=",", fmt="%.7g")


def synthetic_capture(args: argparse.Namespace, output: Path) -> dict[str, object]:
    rng = np.random.default_rng(args.seed)
    samples = int(round((args.pre_trigger_ns + args.post_trigger_ns) / args.sample_interval_ns)) + 1
    time_ns = np.linspace(-args.pre_trigger_ns, args.post_trigger_ns, samples)
    status_rows: list[tuple[int, int, float]] = []
    started = time.monotonic()

    for event in range(args.events):
        traces = {channel: rng.normal(0.0, 2.5, samples) for channel in CHANNELS}
        reference_event = rng.random() > 0.04
        arrival = rng.normal(10.0, 2.0)
        if reference_event:
            for channel, amplitude in (("C", 420.0), ("D", 380.0)):
                traces[channel] += amplitude * rng.lognormal(0.0, 0.18) * pulse_shape(time_ns, arrival)
            for channel, miss_probability, scale in (("A", 0.025, 360.0), ("B", 0.055, 330.0)):
                if rng.random() > miss_probability:
                    traces[channel] += scale * rng.lognormal(0.0, 0.30) * pulse_shape(
                        time_ns, arrival + rng.normal(4.0, 1.0)
                    )
        for channel in ("A", "B"):
            if rng.random() < 0.035:
                traces[channel] += 32.0 * pulse_shape(time_ns, rng.uniform(-500.0, 180.0))
        write_waveform(output / f"event_{event:06d}.csv", time_ns, traces)
        status_rows.append((event, 0, time.monotonic() - started))

    write_status(output, status_rows)
    return {
        "mode": "synthetic",
        "events": args.events,
        "enabled_channels": list(CHANNELS),
        "trigger_channel": args.trigger_channel,
        "trigger_mv": args.trigger_mv,
        "sample_interval_ns": args.sample_interval_ns,
        "pre_trigger_ns": args.pre_trigger_ns,
        "post_trigger_ns": args.post_trigger_ns,
    }


def write_status(output: Path, rows: list[tuple[int, int, float]]) -> None:
    with (output / "event_status.csv").open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle)
        writer.writerow(["event", "overflow_mask", "elapsed_s"])
        writer.writerows(rows)


def hardware_capture(args: argparse.Namespace, output: Path) -> dict[str, object]:
    scope = PicoBlockScope(args.driver, max(args.channel_ranges_mv.values()))
    scope.open()
    try:
        scope.configure_channels(args.enabled_channels, args.channel_ranges_mv)
        trigger_at_input_mv = args.trigger_mv / args.channel_attenuations[args.trigger_channel]
        coincidence_trigger_at_input_mv = None
        if args.coincidence_channel is None:
            scope.configure_trigger(
                args.trigger_channel,
                trigger_at_input_mv,
                args.auto_trigger_ms,
                enabled=True,
            )
        else:
            coincidence_trigger_at_input_mv = (
                args.coincidence_trigger_mv
                / args.channel_attenuations[args.coincidence_channel]
            )
            scope.configure_coincidence_trigger(
                args.trigger_channel,
                trigger_at_input_mv,
                args.coincidence_channel,
                coincidence_trigger_at_input_mv,
                args.auto_trigger_ms,
            )
        approximate_samples = int(
            round((args.pre_trigger_ns + args.post_trigger_ns) / args.sample_interval_ns)
        ) + 1
        timebase, actual_interval_ns = scope.find_timebase(
            approximate_samples, args.sample_interval_ns
        )
        pre_samples = int(round(args.pre_trigger_ns / actual_interval_ns))
        post_samples = int(round(args.post_trigger_ns / actual_interval_ns)) + 1
        time_ns = (np.arange(pre_samples + post_samples) - pre_samples) * actual_interval_ns
        status_rows: list[tuple[int, int, float]] = []
        overflow_events = 0
        started = time.monotonic()

        for event in range(args.events):
            traces_at_input, overflow = scope.capture_channels(
                pre_samples,
                post_samples,
                timebase,
                args.enabled_channels,
            )
            traces = {
                channel: traces_at_input[channel] * args.channel_attenuations[channel]
                for channel in args.enabled_channels
            }
            for channel in CHANNELS:
                if channel not in traces:
                    traces[channel] = np.full(len(time_ns), np.nan)
            overflow_events += int(bool(overflow))
            status_rows.append((event, overflow, time.monotonic() - started))
            write_waveform(output / f"event_{event:06d}.csv", time_ns, traces)
            if (event + 1) % 100 == 0:
                elapsed = time.monotonic() - started
                rate = (event + 1) / elapsed if elapsed > 0 else 0.0
                print(f"captured {event + 1}/{args.events} events ({rate:.2f} events/s)", flush=True)

        write_status(output, status_rows)
        return {
            "mode": "hardware",
            "driver": scope.driver,
            "events": args.events,
            "overflow_events": overflow_events,
            "enabled_channels": list(args.enabled_channels),
            "scope_input_ranges_mV": scope.channel_ranges,
            "probe_tip_ranges_mV": {
                channel: value * args.channel_attenuations[channel]
                for channel, value in scope.channel_ranges.items()
            },
            "probe_attenuations": args.channel_attenuations,
            "timebase": timebase,
            "sample_interval_ns": actual_interval_ns,
            "pre_samples": pre_samples,
            "post_samples": post_samples,
            "trigger_channel": args.trigger_channel,
            "trigger_mv_at_probe_tip": args.trigger_mv,
            "trigger_mv_at_scope_input": trigger_at_input_mv,
            "coincidence_channel": args.coincidence_channel,
            "coincidence_trigger_mv_at_probe_tip": args.coincidence_trigger_mv,
            "coincidence_trigger_mv_at_scope_input": coincidence_trigger_at_input_mv,
            "auto_trigger_ms": args.auto_trigger_ms,
            "elapsed_s": time.monotonic() - started,
        }
    finally:
        scope.close()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--events", type=int, default=5000)
    parser.add_argument("--driver", choices=("auto",) + SUPPORTED_DRIVERS, default="ps3000a")
    parser.add_argument("--enabled-channels", type=parse_channels, default=parse_channels("A,B,C,D"))
    parser.add_argument(
        "--channel-ranges-mv",
        type=parse_ranges,
        default=parse_ranges("A=500,B=500,C=500,D=500"),
        help="per-channel scope-input ranges; probe-tip range is this value times attenuation",
    )
    parser.add_argument(
        "--probe-attenuation",
        type=float,
        default=10.0,
        help="legacy common attenuation used when --channel-attenuations is omitted",
    )
    parser.add_argument(
        "--channel-attenuations",
        type=parse_attenuations,
        help="per-channel physical probe ratios, for example A=10,B=10,C=1,D=1",
    )
    parser.add_argument("--sample-interval-ns", type=float, default=2.0)
    parser.add_argument("--pre-trigger-ns", type=float, default=800.0)
    parser.add_argument("--post-trigger-ns", type=float, default=400.0)
    parser.add_argument("--trigger-channel", choices=CHANNELS, default="C")
    parser.add_argument("--trigger-mv", type=float, default=100.0)
    parser.add_argument(
        "--coincidence-channel",
        choices=CHANNELS,
        help="optional second reference channel for a hardware analogue coincidence",
    )
    parser.add_argument(
        "--coincidence-trigger-mv",
        type=float,
        help="second-channel threshold at the probe tip; defaults to --trigger-mv",
    )
    parser.add_argument("--auto-trigger-ms", type=int, default=10000)
    parser.add_argument("--synthetic", action="store_true")
    parser.add_argument("--seed", type=int, default=20260921)
    args = parser.parse_args()

    if args.events < 1:
        parser.error("--events must be positive")
    if args.trigger_channel not in args.enabled_channels:
        parser.error("the trigger channel must be enabled")
    if args.coincidence_channel is not None:
        if args.coincidence_channel not in args.enabled_channels:
            parser.error("the coincidence channel must be enabled")
        if args.coincidence_channel == args.trigger_channel:
            parser.error("the coincidence channel must differ from the trigger channel")
        if args.coincidence_trigger_mv is None:
            args.coincidence_trigger_mv = args.trigger_mv
    elif args.coincidence_trigger_mv is not None:
        parser.error("--coincidence-trigger-mv requires --coincidence-channel")
    if any(channel not in args.channel_ranges_mv for channel in args.enabled_channels):
        parser.error("every enabled channel needs a channel range")
    if args.channel_attenuations is None:
        if not math.isfinite(args.probe_attenuation) or args.probe_attenuation <= 0:
            parser.error("--probe-attenuation must be positive")
        args.channel_attenuations = {
            channel: args.probe_attenuation for channel in args.enabled_channels
        }
    if any(channel not in args.channel_attenuations for channel in args.enabled_channels):
        parser.error("every enabled channel needs a probe attenuation")
    if any(
        not math.isfinite(args.channel_attenuations[channel])
        or args.channel_attenuations[channel] <= 0
        for channel in args.enabled_channels
    ):
        parser.error("all channel attenuations must be positive")
    args.output.mkdir(parents=True, exist_ok=False)
    metadata = synthetic_capture(args, args.output) if args.synthetic else hardware_capture(args, args.output)
    metadata.update(
        {
            "captured_at_utc": datetime.now(timezone.utc).isoformat(),
            "output": str(args.output.resolve()),
        }
    )
    (args.output / "capture_metadata.json").write_text(
        json.dumps(metadata, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(metadata, indent=2))


if __name__ == "__main__":
    main()
